#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_FRAME_DELAY_MS 100
#define CONFIG_X_BOUNDARY 20
#define CONFIG_Y_BOUNDARY 20
#define CONFIG_SNAKE_STARTING_TAIL_COORDS 10, 10
#define CONFIG_SNAKE_STARTING_SIZE 1
#define CONFIG_SNAKE_STARTING_DIRECTION Snake::right

#endif // CONFIG_H
